name: Build Docker Image

on:
  push:
    branches:
      - development
    paths:
      - frontend/**

env:
  CURRENT_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/erm_versionhub-frontend:$GITHUB_SHA-dev"
  LATEST_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/erm_versionhub-frontend:latest"

jobs:
  build:
    name: Building and pushing frontend image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t $CURRENT_TAG frontend
          
      - name: Push Docker image
        run: |
          docker tag $CURRENT_TAG $LATEST_TAG
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $CURRENT_TAG
          docker push $LATEST_TAG