on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs:
  build:
      name: Buliding test on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      steps:
      - uses: ./eRM_VersionHub
      - run: dotnet build
